language: node_js
node_js:
  - "8.9.1"

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools

after_success:
  - firebase deploy --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN