language: node_js
node_js:
  - "12.14.1"

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools
  - npm i

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT